name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  toolchains:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ nightly, beta, stable, 1.66.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust ${{matrix.toolchain}}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: All features
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "--cfg bench"
        with:
          command: check
          args: --workspace --all-targets --all-features
